= JSON report format
:page-date: 2019-03-29 00:00:00 Z
:page-last_modified_at: 2019-12-17 00:00:00 Z

JSON is treated as Human Machine Interface, e.g. values etc.
are truncated the same way as with text output, and all data is represented 
as strings.

This means reports in JSON format should be ready to be displayed
to user by UI as they are without further processing or data formatting.

JSON output does not contain null values, e.g. if field is null, it is dropped.

xref:./client-api.adoc[Client API] lists used data models for JSON serialization.

== Example reports

Supported reports with JSON output are `balance`, `balance-group` and `register`.
Exports in Tackler journal format (`equity` and `identity`) are not supported with JSON.

=== Balance report

* {repolink}/tests/commodity/ok/basic-03.ref.bal.json/[Balance with commodities]
* {repolink}/tests/audit/ok/audit-1E2-04.ref.bal.json/[Balance with Metadata]

=== Balance Group report

* {repolink}/tests/commodity/ok/basic-03.ref.balgrp.json/[Balance-group with Commodities]
* {repolink}/tests/audit/ok/audit-1E2-04.ref.balgrp.json/[Balange-group with Metadata]
* {repolink}/tests/audit/ok/audit-1E1-01.ref.balgrp.json/[Balange-group with Report Timezone Metadata]

=== Register report

* {repolink}/tests/commodity/ok/basic-03.ref.reg.json/[Register report with Commodities]
* {repolink}/tests/audit/ok/audit-1E2-04.ref.reg.json/[Register report with Metadata]
* {repolink}/tests/audit/ok/audit-1E1-01.ref.reg.json/[Register report with Report Timezone Metadata]
* {repolink}/tests/tags/ok/basic-01.ref.reg.json/[Register report with Txn Tags]