= Quickstart
:page-date: 2019-03-29 00:00:00 Z
:page-last_modified_at: 2019-05-09 00:00:00 Z
:page-permalink: /docs/quickstart/


Minimal tackler setup can be created by following four steps:

.1. Create directory structure for demo setup
----
mkdir tackler
mkdir tackler/txns

# Change current working directory to tackler demo folder
cd tackler

# "Install" tackler-cli.jar
cp /path/to/tackler-cli-x.y.z.jar ./tackler-cli.jar
----

The journal data file (`txns/journal.txn`) can not be empty,
hence we have to create some transactions to play with it.

.2. Create some transactions
----
cat > txns/journal.txn << EOF
2018-06-01 'First transaction
 Expenses:Ice_cream  2
 Assets:Cash

2018-06-02 'Second transaction
 Expenses:Lemonade  1
 Assets:Cash

EOF
----

After these steps, content of tackler demo folder should be:

.3. Verify setup
----
./tackler-cli.jar
./txns/
./txns/journal.txn
----

With above setup we are ready to generate default reports based
on tackler's embedded configuration.

.4. Generate default Balance and Register reports
----
# This command must be run inside 'tackler' folder, which was created abobe
java -jar ./tackler-cli.jar --accounts.strict=false

# ... Log lines suppressed ...
# ... There are legitime ERROR and WARNING about missing configuration ...
# ... See Installation Manual how to configure tackler ...
# 
Txns size: 2

BALANCE
-------
                 0.00   -3.00  Assets
                -3.00   -3.00  Assets:Cash
                 0.00    3.00  Expenses
                 2.00    2.00  Expenses:Ice_cream
                 1.00    1.00  Expenses:Lemonade
=====================
                 0.00


REGISTER
--------
2018-06-01Z 'First transaction
            Assets:Cash                                   -2.00              -2.00
            Expenses:Ice_cream                             2.00               2.00
----------------------------------------------------------------------------------
2018-06-02Z 'Second transaction
            Assets:Cash                                   -1.00              -3.00
            Expenses:Lemonade                              1.00               1.00
----------------------------------------------------------------------------------


Total processing time: 1284, parse: 464, reporting: 80
----

This minimal setup is based on default embedded configuration
and tackler's auto-discovery mechanism for journal data.

See xref:./journal/format.adoc[Journal Format],
xref:./installation.adoc[Installation Manual]
and xref:./usage.adoc[Usage Guide] how to
further configure tackler and use it with more production like setup.
