= Reliability
:page-date: 2019-03-29 00:00:00 Z
:page-last_modified_at: 2019-03-29 00:00:00 Z

[quote]
____
Simplicity is prerequisite for reliability +
as reliability is for integrity +
when integrity is the essence of trust.
____


== Testing

All tackler's features must be tested, and overell test coverage 
should be almost perfect.  Tackler is tested with functional and 
logical test sets to ensure that all logical code paths are covered.

At the moment, Tackler test coverage is better than *99.7%*.

Tackler has *99* tracked features. For those 99 features, tackler has
over *500* test cases, tackler-cli is executed over *160* times by test setup,
and results are verified by over *400* reference reports.

=== Performance

Accounting Journal with size of *one hundred thousand* (1E5) transactions 
is used with integration tests
(see: {gitlink}/core/src/it/scala/fi/e257/tackler/parser/TacklerTxnsGitTest.scala[TacklerTxnsGitTest])
and tackler is stress and performance tested with up to *one million* (1E6)
transactions test sets.  On laptop, tackler can process over 30 000 txn/s.
See xref:./performance.adoc[Performance Overview] for details
or {gitlink}/docs/devel/build.adoc[test it yourself].


=== Tackler Test Tracking Database

{gitlink}/tests/tests.adoc[Tackler Test Tracking Database (T3DB)] tracks features
and tests for those features. T3DB is used to ensure that all features 
and error paths for those features are tested, that test setup has as little as 
possible of overlapping tests and prevent  duplicate test cases.

T3DB also provides reverse mapping from a test case back to the feature,
which is validated by that test case.
