### vim: tabstop=2 shiftwidth=2 softtabstop=2 smarttab expandtab autoindent
###
### E257.FI: tackler
### https://gitlab.com/e257/accounting/tackler
###

# hseeberger images have ready-to-go sbt and scala at user's home, 
# but that location and especially ~/.ivy2 is not cache-able by GitLab:
# https://gitlab.com/gitlab-org/gitlab-runner/issues/327
before_script:
  - mkdir -p sbt-cache
  - mkdir -p sbt-cache/coursier
  - "[ -d sbt-cache/sbt ] || cp -a $HOME/.sbt/  sbt-cache/sbt"
  - "[ -d sbt-cache/coursier/cache ] || cp -a $HOME/.cache/coursier/v1 sbt-cache/coursier/cache"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  untracked: true
  paths:
    - "sbt-cache/sbt/1.0"
    - "sbt-cache/sbt/boot"
    - "sbt-cache/coursier/cache"

variables:
  SBT_OPTS: "-Dsbt.log.noformat=true -Dsbt.global.base=sbt-cache/sbt/1.0 -Dsbt.boot.directory=sbt-cache/sbt/boot -Dsbt.coursier.home=sbt-cache/coursier/cache"


test·jdk11:
  image: "hseeberger/scala-sbt:11.0.13_1.6.1_2.13.7"

  stage: "test"

  script:
    - sbt "clean" "test" "it:test" "cli/assembly"


codecov:
  image: "hseeberger/scala-sbt:11.0.13_1.6.1_2.13.7"

  stage: "test"

  script:
    - sbt "clean" coverage "test" "it:test"
    - sbt "coverageAggregate"

  coverage: '/All done. Coverage was stmt=\[\d+.\d+%\]/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/scala-2.13/coverage-report/cobertura.xml

