### vim: tabstop=2 shiftwidth=2 softtabstop=2 smarttab expandtab autoindent
###
### E257.FI: tackler
### https://gitlab.com/e257/accounting/tackler
###

# hseeberger images have ready-to-go sbt and scala at user's home, 
# but that location and especially ~/.ivy2 is not cache-able by GitLab:
# https://gitlab.com/gitlab-org/gitlab-runner/issues/327
before_script:
  - mkdir -p sbt-cache
  - mkdir -p sbt-cache/coursier
  - "[ -d sbt-cache/sbt ] || cp -a $HOME/.sbt/  sbt-cache/sbt"
  - "[ -d sbt-cache/coursier/cache ] || cp -a $HOME/.cache/coursier/v1 sbt-cache/coursier/cache"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  untracked: true
  paths:
    - "sbt-cache/sbt/1.0"
    - "sbt-cache/sbt/boot"
    - "sbt-cache/coursier/cache"

variables:
  SBT_OPTS: "-Dsbt.log.noformat=true -Dsbt.global.base=sbt-cache/sbt/1.0 -Dsbt.boot.directory=sbt-cache/sbt/boot -Dsbt.coursier.home=sbt-cache/coursier/cache"


test·jdk11:
  image: "hseeberger/scala-sbt:11.0.4_1.3.5_2.13.1"

  stage: "test"

  script:
    - sbt "+clean" "+test" "+it:test" "+cli/assembly"


test·jdk8:
  image: "hseeberger/scala-sbt:8u222_1.3.5_2.13.1"

  stage: "test"

  script:
    - sbt "+clean" "+test" "+it:test" "+cli/assembly"


###
### Use scala 2.13.0 for coverate until
### https://github.com/scoverage/sbt-scoverage/issues/295
### is fixed
codecov:
  image: "hseeberger/scala-sbt:8u222_1.3.5_2.13.1"

  stage: "test"

  script:
    - sbt "+clean" coverage "++2.13.1! test" "++2.13.1! it:test"
    - sbt "++2.13.1! coverageAggregate"

  coverage: '/All done. Coverage was \[\d+.\d+%\]/'

