### vim: tabstop=2 shiftwidth=2 softtabstop=2 smarttab expandtab autoindent
###
### E257.FI: tackler
### https://gitlab.com/e257/tackler
###
cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - "sbt-cache/ivy/cache"
    - "sbt-cache/boot"
    - "sbt-cache/sbtboot"

test·jdk11:
  image: "hseeberger/scala-sbt:11.0.1_2.12.8_1.2.7"

  variables:
    SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"

  stage: "test"

  script:
    - sbt clean test


test·jdk8:
  image: "hseeberger/scala-sbt:8u181_2.12.7_1.2.6"

  variables:
    SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"

  stage: "test"

  script:
    - sbt clean coverageOn test coverageReport
    - sbt coverageAggregate

  coverage: '/All done. Coverage was \[\d+.\d+%\]/'
