= Contributor's Guide

Contributions to the project are most welcome!


== Open and planned tasks

At the moment project todo items are maintained in link:../todo/[todo files].
Before starting working on something, please first check with Gitlab issue
if your plan is feasible and viable from project's perspective.


== How to build and test

. You do have sbt, don't you? If not, get it from here: http://www.scala-sbt.org/[http://www.scala-sbt.org/]
+
. Get source code
+
    git clone https://gitlab.com/e257/accounting/tackler.git
    cd tackler
+
. Build and test
.. Build and run tests
+
    sbt clean test
+
.. Generate test coverage reports
+
    sbt clean coverageOn test coverageReport
    sbt coverageAggregate

== Explore code

Directory structure follows Maven's layout and code has been divided to sub-projects

link:./api[api]::
Tackler Api (`tackler-api`)
+
** link:./api/src/main/scala/fi/e257/tackler/api/[api -> scala -> api] Client API (JVM and JS)
+
link:./core[core]::
Tackler Core (`tackler-core`)
+
** link:./core/src/main/antlr4/[core -> antlr4] ANTLR4 Grammar definition for Tackler input
** link:./core/src/main/java/fi/e257/tackler/parser/[core -> java -> parser] Java helpers for parser
** link:./core/src/main/scala/fi/e257/tackler/parser/[core -> scala -> parser] Scala interface for Parser
** link:./core/src/main/scala/fi/e257/tackler/model/[core -> scala -> model]  Model object (Txn, Posting, etc)
** link:./core/src/main/scala/fi/e257/tackler/core/[core -> scala -> core] Core modules
** link:./core/src/main/scala/fi/e257/tackler/report/[core -> scala -> report] Reporting code
+
link:./cli[cli]::
* link:./cli/src/main/scala/fi/e257/tackler/cli/[cli -> scala -> cli] Command Line Interface code
+
link:./tests[tests]::
link:https://github.com/sn127/utils[DirSuite] based integration tests for Tackler.
+
** link:./tests/tests.yaml[tests -> tests.yaml] List of all tests and tested features
** link:./tests/accumulator[tests -> accumulator] Tests for validating calculator and Accumulator operations
** link:./tests/cli[tests -> cli] Tests for Command Line Interface verification
** link:./tests/parser[tests -> parser] Parser and input recognition tests (valid and non-valid input)
** link:./tests/core[tests -> core] Tests for core components and features
** link:./tests/reporting[tests -> reporting] Tests to validate reporting
** link:./tests/reset-ref.sh[tests -> reset-ref.sh] Tool to reset reference vectors with current output

=== API documents

Also see link:docs/devel/readme.adoc[developer's documentation] and link:./docs/server-api.adoc[Server API] and link:./docs/client-api.adoc[Client API].

== Developer Certificate of Origin

Your pull requests and patches can be merged only if you can certify
the link:./DCO[Developer Certificate of Origin (DCO), Version 1.1].

By signing-off your commit you certify DCO and acknowlegde that you have
the rights to submit your pull requsted or patch as an open-source patch,
as stated in link:./DCO[Developer Certificate of Origin].

Certifying DCO is done by adding a `Signed-off-by` line
to **every** git commit message:

    Signed-off-by: gitlab-account <your.real@email.address>

If you set your `user.name` and `user.email` correctly in git config,
then git will automatically include that line for you with `git commit -s`.
You can also create a git `commit.template` with appropriate content. These
settings can be done per repository basis,  so they don't have to be globally
set in your system.
 
Please make sure that you sign-off all your PR's commits.

