= Contributor's Guide

Contributions to the project are most welcome!


== Open and planned tasks

At the moment project todo items are maintained in xref:../todo/[todo files].
Before starting working on something, please first check by opening Gitlab issue
if your plan is feasible and viable from project's perspective.

=== Tackler Enhancements Proposals

Bigger changes to Tackler are done via Tackler Enhancements Proposals.

These are tracked on xref:./docs/tep/readme.adoc[TEP Index]. There is template
for new TEP here: xref:./docs/tep/tep-0001.adoc[TEP template]


== How to build and test

. You do have sbt, don't you? If not, get it from here: http://www.scala-sbt.org/[http://www.scala-sbt.org/]
+
. Get source code
+
    git clone https://gitlab.com/e257/accounting/tackler.git
    cd tackler
+
. Build and test
.. Build and run tests
+
    sbt clean test
+
.. Generate test coverage reports
+
    sbt clean coverageOn test coverageReport
    sbt coverageAggregate

== Documentation for Tackler developers

xref:./docs/devel/readme.adoc[Developer's Guide] for Tackler located under
xref:./docs/devel/[docs -> devel].


== Explore code

Directory structure follows Maven's layout and code has been divided to sub-projects

xref:./api[api]::
Tackler Api (`tackler-api`)
+
** xref:./api/src/main/scala/fi/e257/tackler/api/[api -> scala -> api] Client API (JVM and JS)
+
xref:./core[core]::
Tackler Core (`tackler-core`)
+
** xref:./core/src/main/antlr4/[core -> antlr4] ANTLR4 Grammar definition for Tackler input
** xref:./core/src/main/java/fi/e257/tackler/parser/[core -> java -> parser] Java helpers for parser
** xref:./core/src/main/scala/fi/e257/tackler/parser/[core -> scala -> parser] Scala interface for Parser
** xref:./core/src/main/scala/fi/e257/tackler/model/[core -> scala -> model]  Model object (Txn, Posting, etc)
** xref:./core/src/main/scala/fi/e257/tackler/core/[core -> scala -> core] Core modules
** xref:./core/src/main/scala/fi/e257/tackler/report/[core -> scala -> report] Reporting code
+
xref:./cli[cli]::
* xref:./cli/src/main/scala/fi/e257/tackler/cli/[cli -> scala -> cli] Command Line Interface code
+
xref:./tests[tests]::
This directory contains link:https://gitlab.com/e257/testing/dirsuite[DirSuite] based integration tests for Tackler.
+
** xref:./tests/tests.adoc[tests -> tests.adoc] General overview of tests and Tackler Test Tracking Database (T3DB)
** xref:./tests/accumulator[tests -> accumulator] Tests for validating calculator and Accumulator operations
** xref:./tests/cli[tests -> cli] Tests for Command Line Interface verification
** xref:./tests/parser[tests -> parser] Parser and input recognition tests (valid and non-valid input)
** xref:./tests/core[tests -> core] Tests for core components and features
** xref:./tests/reporting[tests -> reporting] Tests to validate reporting
** xref:./tests/reset-refs.sh[tests -> reset-refs.sh] Tool to reset reference vectors with current output

=== API documents

For API documents, see:

 * xref:./docs/devel/readme.adoc[Developer's Guide]
 * xref:./docs/server-api.adoc[Server API]
 * xref:./docs/client-api.adoc[Client API].

== Developer Certificate of Origin

Your pull requests and patches can be merged only if you can certify
the xref:./DCO[Developer Certificate of Origin (DCO), Version 1.1].

By signing-off your commit you certify DCO and acknowlegde that you have
the rights to submit your pull requsted or patch as an open-source patch,
as stated in xref:./DCO[Developer Certificate of Origin].

Certifying DCO is done by adding a `Signed-off-by` line
to **every** git commit message:

    Signed-off-by: gitlab-account <your.real@email.address>

If you set your `user.name` and `user.email` correctly in git config,
then git will automatically include that line for you with `git commit -s`.
You can also create a git `commit.template` with appropriate content. These
settings can be done per repository basis,  so they don't have to be globally
set in your system.
 
Please make sure that you sign-off all your PR's commits.

