image:https://gitlab.com/e257/accounting/tackler/badges/master/build.svg["Build status", link="https://gitlab.com/e257/accounting/tackler/-/jobs/"]
image:https://gitlab.com/e257/accounting/tackler/badges/master/coverage.svg["Coverage", link="https://gitlab.com/e257/accounting/tackler/-/jobs/"]
image:https://api.bintray.com/packages/e257/tackler/tackler-cli/images/download.svg[link="https://bintray.com/e257/tackler/tackler-cli/_latestVersion"]
image:https://maven-badges.herokuapp.com/maven-central/fi.e257/tackler-core_2.12/badge.svg["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/fi.e257/tackler-core_2.12"]
image:https://javadoc.io/badge/fi.e257/tackler-core_2.12.svg?color=blue["javadoc", link="https://javadoc.io/page/fi.e257/tackler-core_2.12/latest/fi/e257/tackler/index.html"]
image:https://www.scala-js.org/assets/badges/scalajs-0.6.17.svg["Scala.js",link="https://www.scala-js.org"]

= Tackler

Tackler Ain't Calculator and Kernel for link:http://ledger-cli.org/[Ledger] Equivalent Records.
Why not?  - Because it uses simplified Ledger syntax.

So in other words, Tackler is accounting engine and reporting tool for link:http://plaintextaccounting.org/[text
based double-entry accounting].


== Features

* Supports for link:./docs/auditing.adoc[Accounting Auditing and Assurance]
* Tackler's link:tests/tests.adoc[all features are extensively tested]
* Support for link:docs/commodities.adoc[Commodities] and link:docs/currencies.adoc[Currencies]
* Native support for link:docs/git-storage.adoc[GIT based journal storage]
* Clean and simple link:docs/journal.adoc[journal format]
* Strict account and commodity name validation with link:./docs/accounts.conf[Chart of Accounts]
* Multiple report and export types:
** link:docs/report-balance.adoc[Balance], link:docs/report-balance-group.adoc[Balance Groups] and link:docs/report-register.adoc[Register] Reports
** link:docs/export-equity.adoc[Equity] and link:docs/export-identity.adoc[Identity] Exports
* Support for link:./docs/txn-filters.adoc[Transaction Filters]
* Supports UTF-8 characters in transaction data (link:tests/parser/ok/par-02.ref.identity.txn[descriptions], link:tests/parser/ok/par-02.ref.reg.txt[comments], link:tests/parser/ok/id-chars-01.ref.identity.txn[account names])
* Supports ISO 8601 timestamps with link:tests/core/ok/time-dst-01.ref.identity.txn[timezones]
  and link:tests/core/ok/time-nano-01.ref.identity.txn[nanosecond] resolution
* Text and link:docs/json.adoc[JSON] output formats for reports
** link:docs/server-api.adoc[Server API] for embedding Tackler core
** link:docs/client-api.adoc[Client API] for JVM and JS environments
* Has good performance with link:docs/performance.adoc[large transaction set]
** Tackler is link:perf/results/perf-hw00.adoc[tested up to one million (1E6)] transactions
** Tackler can parse and process link:perf/results/readme.adoc[56000 txn/s] on Quad Core system
* link:docs/readme.adoc[Extensive documentation]


== Why Tackler?

Tackler's idea is provide *concise*, *minimal* and *reliable*
engine to process text-based human readable accounting records.

_Concise_ means that Tackler's journal format is semantically concise
and easy for humans to *reason about*.

_Minimal_ means that Tackler provides *minimum* set of features which are
needed for its operation.

_Reliable_ means that Tackler's behaviour is well known, tested
and it is *documented*.

All that said, Tackler can be used easily from command line
with normal personal accounting data sets.


=== Tackler Goals

* Minimal feature set, very simple and well defined input format
** *Tackler input journal is supposed to be produced by software and to be audited by human.* +
    However, it must be possible to edit the journal by hand.

* Well known and defined behaviour

* Extensive user and developer documentation

* Error free, reliable and resilient
** Near perfect code and permutation test coverage

* Good performance
** Must be able to process hundreds of thousands of records with reasonable processing time and memory footprint
** Must have linear processing time characteristics
** Assumption: All transactions can be held in memory

* Provides backend and core components for text based accounting processing

* JVM and Multi platform support: Linux and Arm-Linux, it should be possible to run it on Windows

* GIT is used for data distribution and storage

Implementation language of Tackler is link:http://scala-lang.org/[Scala] 
and journal parsing is done with link:http://www.antlr.org/[ANTLR4].


== Documentation and Quick Start Guides

Full list of available documentation is located on link:./docs/readme.adoc[Index of Documentation].

For quick start information, see:

* link:./docs/installation.adoc[Installation Manual]
* link:./docs/journal.adoc[Tackler journal format]
* link:./docs/usage.adoc[Usage Guide]
* link:./docs/tackler.conf[tackler.conf] for annotated configuration file
* link:./docs/accounts.conf[accounts.conf] for annotated chart of accounts


== Todo, TEPs and Roadmap

At the moment, current set of active todo items is kept link:./todo[todo files].

There are Tackler Enhancement Proposals for planning and tracking implementation
of major new features. These are listed on link:docs/tep/readme.adoc[TEP index].

=== Roadmap

Extremely loosely defined roadmap is following:

* Reporting Server as separate project 
* Extending support for Units
* Profit and Loss (PnL) tracking
** Automatic conversions between different base units
** Support for unit handling with commodities  
* Extending support for Currencies and Commodities
** Price database

== Releases

For release information and version history details,
see link:./CHANGELOG.adoc[CHANGELOG].

Tackler-core is supposed to be usable as separate component.
Tackler-api is released for JVM and JS environments, and it is intended
to be used on the client side. See link:./docs/server-api.adoc[Server API]
and link:./docs/client-api.adoc[Client API] for additional information.

Dependency settings for SBT are:

    libraryDependencies += "fi.e257" %%  "tackler-core" % "version-number"
    libraryDependencies += "fi.e257" %%% "tackler-api"  % "version-number"

These are released on Maven Central Repository.

Tackler is under development, so if you enjoy calm seas
then it might be better to look
link:http://plaintextaccounting.org/[something else].

However, complex backward non-compatible changes to 
link:./docs/journal.adoc[Journal file format]
should be rare. At the moment Tackler is used in production for
operational data set.

Configuration files, command line interface and Client API (data models)
are more likely to subject of change.


== Contributing to Tackler

Contributions to the project are most welcome. See
link:./CONTRIBUTING.adoc[CONTRIBUTING] how you could help.

Your pull requests and patches can be merged only if you can certify
the link:./DCO[Developer Certificate of Origin (DCO), Version 1.1].

By signing-off your commit you certify DCO and acknowlegde that you have
the rights to submit your pull requsted or patch as an open-source patch,
as stated in link:./DCO[Developer Certificate of Origin].

Certifying DCO is done by adding a `Signed-off-by` line
to **every** git commit message:

    Signed-off-by: gitlab-account <your.real@email.address>

If you set your `user.name` and `user.email` correctly in git config,
then git will automatically include that line for you with `git commit -s`.
You can also create a git `commit.template` with appropriate content. These
settings can be done per repository basis,  so they don't have to be globally
set in your system.
 
Please make sure that you sign-off all your PR's commits.


== Credits

See link:./THANKS.adoc[THANKS] for full list of credits.


== License

....
Copyright 2016-2019 E257.FI Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
....

