= Journal Format
:page-layout: page

Tacklers journal is based on idea of link:https://plaintextaccounting.org/[plain text files], 
where each accounting record is written in human readable and editable form into those text files. 
This idea of text based double-entry accounting was 
link:https://www.ledger-cli.org/[invented and pioneered] by John Wiegley in 2003.

[NOTE]
Tackler Ain't Calculator and Kernel for link:http://ledger-cli.org/[Ledger] Equivalent Records. + 
Why not? Because it uses simplified syntax.

== Journal files

Journal can be a single file or it can be split on transaction level into multiple files (shards).

See general link:/docs/journal/[Journal Documentation], 
xref:../usage.adoc[Usage Manual] and 
xref:../tackler-conf.adoc[tackler.conf] for further defails
how to define used storage system and ideas for different sharding schemes.


== Format

[cols="1,5a,3a", options="header"]
|===
|
| Journal entry
| Comments

| Basic example
|
----
2017-01-01 'Opening balance
 Assets:Checking 500.00
 Equity:Assets

2017-01-05 'Shopping on farmer's market
 Expenses:Groceries 50.00
 Assets:Checking

----
| This is sequence of Transactions (Txns). There could one
or many Txns per input file.


| Basic transaction
|
----
DATE [(code)] [[']DESCRIPTION]
 ACCOUNT  AMOUNT
 ACCOUNT  [AMOUNT]
----
| Transaction's content (comments and account postings) must be intented at least by *one* space. 

There must be two or more accounts (postings) which
must have zero sum if all accounts have amount. Account's amount can not be zero.

Amount of *last* account could be omitted, in that case it will be 
calculated automatically.

There has to be at least one space between account and amount.
If compatibility with other systems is needed, then two spaces should be used.


| Dates and Timestamps
|
----
YYYY-MM-DD
YYYY-MM-DDTHH:MM:SS[.SSS]
YYYY-MM-DDTHH:MM:SS[.SSS]Z
YYYY-MM-DDTHH:MM:SS[.SSS]±hh:mm
----

e.g.

----
2016-12-31
2016-12-31T13:01:01
2016-12-31T13:01:01.123
2016-12-31T13:01:01Z
2016-12-31T13:01:01+02:00
2016-12-31T13:01:01.123456789+02:00
----
| These are link:https://en.wikipedia.org/wiki/ISO_8601[ISO-8601] dates and times with nanosecond resolution.

* If time part is missing then `00:00:00` is used.
* If Offset is missing then offset based on xref:../tackler-conf.adoc[configured] timezone/offset is used.

| Transaction code
|
----
DATE '(' code ')'
----

e.g.

----
2017-01-01 (#123)
 Expences:Jäätelö   2
 Assets:Cash
----
| Optional Transaction code, this could be check number, wire transfer id or 
delivery tracking number, for example. 

Transcation code is terminated by `)` character. 

Do not use following chararters for code,

`'` `(` `)` `[` `]` `{` `}` `<` `>`

even though those are accepted by Tackler at the moment.

| Description
|
----
DATE [[']Description]
----

e.g.

----
2019-03-16 'Ice cream 'n soda!
...
2019-03-16 (#125) 'It was 125th Ice Cream!
...
2017-01-01 Desc without '-prefix is discouraged
----

| Optional Description of transaction, this is similar to subject line of email.

At the moment, Tackler accepts ledger-like freestyle descriptions, but this 
form of transaction description is discouraged. 

Future versions of Tackler might drop support for freestyle descriptions, 
and there should be `'` at the start of description in the future.


| Account names
|
----
TOPACCT[:SUBACCT[:...]]
----

e.g.

----
Expenses:ice_cream
Expenses:jäätelö
Expenses:jäätelö:mansikka-vadelma
Expenses:crème·glacée
Expenses:мороженое
Expenses:アイスクリーム
Expenses:風:空
----
| Account names begin with a UTF-8 letter. Then
letters, digits, middle dot `·`, hyphen `-` and underscore `_` are allowed in account names,
but no spaces.   Sub-accounts are separated by `:`

All accounts must be declared in Chart of Accounts, or `accounts.strict` should be `false`.

See xref:../accounts-conf.adoc[accounts.conf] for full details.


| Amounts
|
----
1234567.1234
Output truncation:
  1.12345678 is printed as 
  1.1234568  with scale.max=7
----
| 
Default *output* scale is is between 2..7 decimal points.  This is can be configured 
by `reporting.scale.{min, max}` in xref:../tackler-conf.adoc[tackler.conf].

Tackler uses decimal floating-point numbers of arbitrary precision (Scala BigDecimals) for calculations.
There are unit tests with numbers of 30 digits and 130 decimals.


| Commodities
|
----
2017-05-01 'In Sweden
 Expences:Ice·Cream  200 SEK
 Assets:Cash
----
| See xref:../commodities.adoc[Commodities]


| Value positions
|
----
2017-05-01 'In Sweden
 Expences:Ice·Cream  200 SEK @ 0.1039 EUR
 Assets:Cash  -20.78 EUR
----
| See xref:../currencies.adoc[Currencies]

| PnL: Opening position
|
----
2017-05-01 'Selling one Acme Inc.
 Stock:Shares -1 ACME·INC {120 EUR} @ 123 EUR
 Assets:Cash 123 EUR
----
| Currently opening position is valid input, but it is not used.
This is planned feature. See xref:../currencies.adoc[Currencies]


| Comments
|
----
2017-01-01 'Txn with comment
 ; txn level comment
 Expenses:groceries 12.00 ; posting comment
 assets:checking
----
| There must be space after `;` character


| Transaction comments
|
----
2017-01-01 'Txn with multiline comment
 ; it was warm
 ; and sunny day
 Expenses:Jäätelö 2.12
 Assets:Cash
----
| Could have multiple comments, there has to be space after `;` char.


| Posting comments
|
----
2017-01-01 'Posting with comment
 Expenses:Jäätelö 2.12 ; Strawberry ice cream!
 Assets:Cash
----
|


| Transaction metadata
|
----
2017-01-01 'Txn with UUID
 ;:uuid: 83976d4b-8ea8-4cec-804f-931e4f171c3b
 Expenses:Ice_cream 2.12
 Assets:Cash
----
| At the moment only supported metadata is `uuid` which is reserved for optional transaction's
unique identifier (link:https://en.wikipedia.org/wiki/Universally_unique_identifier[UUID]).

Transaction UUID is mandatory if `txn-set-checksum` calculation is activated.
See xref:../tackler-conf.adoc[tackler.conf] and {gitlink}/docs/tep/tep-1007.adoc[TEP-1007: Txn Set Checksum]
for further information.

Transactions must have UUIDs, if fully deterministic, stable
and "distributed transaction producers"-safe sort order is needed for xref:../report-register.adoc[register report]
or xref:../export-identity.adoc[identity export].


| Posting metadata
|
----
2017-01-01 'Waporware - not supported
 Expenses:Ice_cream 2.12 ;:date:2017-01-03
 Assets:Cash
----
| *WAPORWARE*

Currently metadata is not supported with postings.

|===


