source "https://rubygems.org"

gem "jekyll", "~> 3.8.5"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
#gem "minima", "~> 2.0"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'jekyll-asciidoc', '~> 2.1.1'
  gem 'jekyll-redirect-from', '~>0.14.0'
  gem 'jekyll-seo-tag'
end

  #gem 'jekyll-feed'
  #gem 'jekyll-sitemap'
