source "https://rubygems.org"

gem "jekyll", "~> 3.8.5"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'jekyll-asciidoc', '~> 2.1.1'
  gem 'jekyll-redirect-from', '~>0.14.0'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
end

  #gem 'jekyll-feed'
