source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "ostruct"
gem "csv"
gem "logger"
gem "base64"

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem 'jekyll-asciidoc'
  gem 'jekyll-redirect-from'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
end

  #gem 'jekyll-feed'
