= Building Tackler


Tackler build is done by link:http://www.scala-sbt.org/[sbt].


== Building and testing

----
LC_ALL=C.UTF-8 sbt clean test
----

=== Running tests

Some of the tests generate lots of output,
especially `cli/test` (and especially `fi.e257.tackler.cli.Dirsuite*` tests).
It might be helpful to run tests selectively, especially in case of errors:

Start `sbt` and run on sbt shell:

....
> apiJVM/test
> core/test
....

For cli tests you could run all at once (`cli/test`), or step-by-step. Last test target, 
Dirsuite-tests will generate supstantial amount of output.

----
> cli/testOnly fi.e257.tackler.cli.BuildInfoTest
> cli/testOnly fi.e257.tackler.cli.TacklerCli*
> cli/testOnly fi.e257.tackler.cli.Dirsuite*
----


== Generating binaries

 sbt cli/assembly


== Code coverage

 sbt clean coveraOn test coverateReport
 sbt coverageAggregate


== IntelliJ

If IntelliJ can not compile e.g. unit tests, make sure that under settings 
for all subprojects (`tackler`, `cli`, `core`) compile order is `java then scala`.

Easiest way to generate parser definition is run `sbt compile`.
You can also install ANTLR plugin, but it must be configured correctly for package-names
and output paths.


== ANTLR

IntelliJ ANTLR plugin has really nice graphical tree display to visualize and test parser rules.



'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the xref:../LICENSE[License] for the specific language governing permissions and limitations under
the xref:../LICENSE[License].
