= TEP-1008: Numeric Account names

Allow account names to start with numbers and/or be numeric only.

Change Tackler Journal file format so that it will accept account names
starting with numbers and/or all numeric account names.  It would be
beneficial to support account names for Credit Cards, Bank Routing numbers,
Bank Account numbers, crypto currencies accounts and wallets, customer/employee numbers,
container ids, etc.

....
Liabilities:CreditCard:1234·4567·8900·0000
Assets:Account:123456-12345678
Address:4zefqrnuz95sw
Helium:Tank:102
....


== Journal file format

Change journal file format so that sub-account name could start
with number and/or be all numeric.  Top-account and commodities and currencies
must still start with UTF-8 letter.

Top-Account::
If top-accounts starts with utf-8 letter, it would leave more room to extend grammar
in the future (for single posting / account).

Commodities::
It would be too confusing if commodities could start with numbers, or be all numeric.

For example:
....
Expences:Ice_Cream  3 000; this is not valid syntax
Assets:Cash
....

== CLI changes

None


== CONF changes

None


== Machinery

Changes to:

* [x] link:../../core/src/main/antlr4/TxnLexer.g4[core -> antlr4 -> TxnLexer]
* [x] link:../../core/src/main/antlr4/TxnParser.g4[core -> antlr4 -> TxnParser]
* [x] link:../../core/src/main/scala/fi/e257/tackler/parser/CtxHandler.scala[core -> parser -> CtxHandler]


=== API changes

None


==== Server API changes

None


==== Client API changes

None


=== New dependencies

None


== Reporting

None


=== Balance report

None


=== Balance Group report

None


=== Register report

None


== Exporting

Changes to exports or exporting

=== Equity export

Equity export generated by post TEP-1008 is not necessarily valid input
for pre TEP-1008 version of Tackler.


=== Identity export

Equity export generated by post TEP-1008 is not necessarily valid input
for pre TEP-1008 version of Tackler.


== Documentation

* [x] xref:./readme.adoc[]: Update TEP index
* [ ] xref:../../CHANGELOG[]: add new item
* [ ] Does it warrant own T3DB file?
** [ ] update xref:../../tests/tests.adoc[]
** [ ] update xref:../../tests/check-tests.sh[]
** [ ] Add new T3DB file xref:../../tests/tests-XXXX.yml[]
* [ ] User docs
** [ ] user manual
*** [ ] journal format
** [ ] accounts.conf


== Future plans and Postponed (PP) features

How and where to go from here?

=== Postponed (PP) features

Anything which wasn't implemented?


== Tests

Normal, ok-case tests to validate functionality:

* [ ] ok accounts
** [ ] `a:0`
** [ ] `a:001`
** [ ] `a:0_0`
** [ ] `a:0-0`
** [ ] `a:0·0`
** [ ] `a:0:abc`
** [ ] `a:001:abc`
** [ ] `a:0_0:abc`
** [ ] `a:0-0:abc`
** [ ] `a:0·0:abc`
** [ ] `a0:0`
** [ ] `a0:001`
** [ ] `a0:0_0`
** [ ] `a0:0-0`
** [ ] `a0:0·0`
** [ ] `a0:001:1_2`
** [ ] `a0:0_0:1-2`
** [ ] `a0:0-0:1·2`
** [ ] `a0:0·0:123`
** [ ] `a0:001:abc`
** [ ] `a0:0_0:abc`
** [ ] `a0:0-0:abc`
** [ ] `a0:0·0:abc`
** [ ] `a:abc:001`
** [ ] `a:abc:0_0`
** [ ] `a:abc:0-0`
** [ ] `a:abc:0·0`
** [ ] `a0:abc:abc`
** [ ] `a0:0123456789`
** [ ] `a0:0123456789:123-456-789`
** [ ] `a0:4zefqrnuz95sw`
* [ ] ok commodity
** [ ] `au`
** [ ] `au_oz`
** [ ] `au-g`
** [ ] `au·kg`
** [ ] `O2_bar`
** [ ] `O2-bar`
** [ ] `O2·bar`
** [ ] `O2_bar_50L`
** [ ] `O2-bar-50L`
** [ ] `O2·bar·50L`
** [ ] `SP500`


=== Errors

Various error cases:

* [ ] e: account names with errors
** [ ] `0`
** [ ] `0:0`
** [ ] `a:0.0`
** [ ] `_0`
** [ ] `_0:a`
** [ ] `·0`
** [ ] `·0:a`
** [ ] `-0`
** [ ] `a:-0:a`
** [ ] `a:_0`
** [ ] `a:_0:a`
** [ ] `a:·0`
** [ ] `a:·0:a`
** [ ] `a:-0`
** [ ] `a:-0:a`
* [ ] e: commodity names with errors
** [ ] `0coin`
** [ ] `0000`
** [ ] `_0`
** [ ] `·0`
** [ ] `-0`

=== Perf

Is there need to run or create new perf tests?

* [ ] perf test

=== Feature and Test case tracking

Feature-id:: bfc11481-21e2-4d12-8d9d-c4b434fd9228

xref:../../tests/tests-XXXX.yml[TEP-XXXX T3DB]


=== Metadata template for test coverage tracking

....
features:
  - feature:
      id: bfc11481-21e2-4d12-8d9d-c4b434fd9228
      subject: "Numeric account names"
      tests:
        errors:
          - error:
              id: 385f7a60-9618-40e4-9f3e-8e28c76a8872
              name: "todo: name of test class/method or test description file"
              desc: "Invalid numerical account names"
          - error:
              id: 78a4af97-a876-4a13-9d67-b7e0ef86ed44
              name: "todo: name of test class/method or test description file"
              desc: "Invalid numerical commodity names"
        operations:
          - test:
              id: 00d410e8-f627-4bb1-a403-0dbe1d64a73a
              name: "todo: name of test class/method or test description file"
              descriptions:
                - desc: "valid numerical accounts"
              references:
                - ref: identity
          - test:
              id: bf61d3a8-8a77-4b8a-917e-1d58acfde25a
              name: "todo: name of test class/method or test description file"
              descriptions:
                - desc: "valid commodity names with numerical parts"
              references:
                - ref: identity

  - feature:
      id: 82b6a8a4-eb91-4d1a-b048-c6ea52d09f6e
      parent: bfc11481-21e2-4d12-8d9d-c4b434fd9228
      subject: "Sub-account name can start with number"
      tests:
        errors:
          - error:
              refid: 385f7a60-9618-40e4-9f3e-8e28c76a8872
              desc: "Number at the begin of name is not allowed for top level account"
          - error:
              refid: 78a4af97-a876-4a13-9d67-b7e0ef86ed44
              desc: "Number at the begin of name is not allowed for commodities"
        operations:
          - test:
              refid: 00d410e8-f627-4bb1-a403-0dbe1d64a73a
              descriptions:
                - desc: "valid sub-accounts"
              references:
                - ref: identity

  - feature:
      id: 01119667-b0ec-41ec-a84b-a4ca915fcc47
      parent: bfc11481-21e2-4d12-8d9d-c4b434fd9228
      subject: "Sub-account name can be fully numerical"
      tests:
        errors:
          - error:
              refid: 78a4af97-a876-4a13-9d67-b7e0ef86ed44
              desc: "Commodities with pure numerical names are not allowed"
        operations:
          - test:
              refid: 00d410e8-f627-4bb1-a403-0dbe1d64a73a
              descriptions:
                - desc: "Fully numerical sub-accounts"
              references:
                - ref: identity
....


'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../../LICENSE[License] for the specific language governing permissions and limitations under
the link:../../LICENSE[License].
