= TEP-1014: Equity Features and Enhancements

See branch
link:https://gitlab.com/e257/accounting/tackler/tree/tep/tep-1014-eq-feat/docs/tep/tep-1014.adoc[/tep/tep-1014-eq-feat]
for actual TEP-1014 content.

New functionalities and enhancements for Equity export


==== Feature and Test case tracking

Feature-id::

* name: Equity Enhancements
* uuid: e5434121-1112-4379-8729-3504912f56a8


link:../../tests/tests-1014.yml[TEP-1014 T3DB]


==== Metadata template for test coverage tracking

....
features:
  - feature:
      id: uuid
      subject: "todo: one-line description of main feature"

  - feature:
      id: uuid
      parent: uuid-of-parent
      subject: "todo: one-line description of sub feature"
      tests:
        errors:
          - error:
              id: uuid
              name: "todo: name of test class/method or test description file"
              desc: "todo: description"
        operations:
          - test:
              id: uuid
              name: "todo: name of test class/method or test description file"
              descriptions:
                - desc: "todo: description"
              references:
                - ref: balance
                - ref: balance-group
                - ref: register
                - ref: identity
                - ref: equity
....


'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../../LICENSE[License] for the specific language governing permissions and limitations under
the link:../../LICENSE[License].
