= TEP-1013: Configuration key change of Accounts CoA

Change Accounts configuration key `coa` to `chart-of-accounts`.

== Summary

Change configuration key of Chart of Accounts  to `chart-of-accounts`, but also support the old key.

If both new and old one are defined at the same time,  then that is hard error.


== Implementation

=== CONF changes

Changes to conf-settings

* [ ] Add `chart-of-accounts`
** [ ] Remove cfg based empty defaults,  so that new-and-old present at the same time case can be detected.


=== Documentation

* [ ] xref:./readme.adoc[]: Update TEP index
* [ ] link:../../CHANGELOG[]: add new item
* [ ] Does it warrant own T3DB file?
** [ ] update xref:../../tests/tests.adoc[]
** [ ] update xref:../../tests/check-tests.sh[]
** [ ] Add new T3DB file xref:../../tests/tests-XXXX.yml[]
* [ ] User docs
** [ ] accounts.conf
*** [ ] `chart-of-accounts`
** [ ] examples
*** [ ] `chart-of-accounts`


=== Future plans and Postponed (PP) features

At some point, move commodities outside of accounts. Provide global main switch for strict mode.


=== Tests

Normal, ok-case tests to validate functionality:

* [ ] New and old setting for CoA
** [ ] old is defined
** [ ] new is defined
** [ ] none is defined


==== Errors

Various error cases:

* [ ] e: old and new are defined at the same time


==== Feature and Test case tracking

Feature-id::

* name: Configuration key change of Accounts CoA
* uuid: 5de84172-6eb7-4d70-acab-ba7c7f5b2114


link:../../tests/tests-1013.yml[TEP-1013 T3DB]


'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../../LICENSE[License] for the specific language governing permissions and limitations under
the link:../../LICENSE[License].
