= Journal format change
:page-date: 2019-03-17 10:00:00 +0200
:page-author: 35vlg84
:page-category: journal



[WARNING]
.Backward incompatible Journal Format Changes between version v1 and v2
====

[horizontal]
Transaction description:: in v2, description must start with `'` -prefix

Transaction code:: in v2, code can not contain  `'` `(` `)` `[` `]` `{` `}` `<` `>` characters

Transaction metadata (uuid):: in v2, metadata must start by ``#`` character with space
====

Tackler v0.24.0 has Phase 1 support for new Journal Format Version v2.
This means that it will accept both old deprecated link:/docs/journal/format/v1/[version v1]
and new link:/docs/journal/format/v2/[version v2] of journal format. All exports
(link:/docs/export-equity/[Equity] and link:/docs/export-identity/[Identity])
are in new format.

[WARNING]
====
Support for old Journal Format Version v1 will be dropped in future release of Tackler.
====

Below are examples of transaction entries which are valid with
Journal Format Version v2.

----
2019-03-03 (#123)
  Expenses:Ice·cream  2
  Assets:Cash

2019-03-04 'Ice cream 'n soda!
  Expenses:Ice·cream  2
  Expenses:Soda  2
  Assets:Cash

2019-03-05 (#125) 'It was 125th ice cream
  # uuid: 9b212495-0c48-4991-a52c-e6684487bd8d
  Expenses:Ice·cream  2
  Assets:Cash
----

See link:/docs/journal/format/[Journal format] for full reference,
and {gitlink}/docs/tep/tep-1009.adoc[TEP-1009: Txn Header Syntax]
for background and motivation of this change.
