= Accounting Auditing and Assurance

Tackler has features to support accounting auditing, assurance and financial audit.

These features are:

 * Proof of used accounting data
 * Proof of used set of transactions
 * Validation of accounts
 * Validation of commodities
 * Proof of used reporting parameters
 * Tackler's test setup

Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../LICENSE[License] for the specific language governing permissions and limitations under
the link:../LICENSE[License].


== Tackler's features for Auditing and Assurance actions


=== Proof of accounting data

Tackler's Git storage backend provides immutable, cryptographic strong evidence of used data.
This information is included in reports' metadata.  It is also possible to rerun reports based on old,
original data, and be assured that same data was used for new calculations that was used originally in the past.

See link:./git-storage.adoc[Git Storage] and link:#examples[examples] section for further details.


=== Proof of used set of transactions

Tackler can provided checksum of transaction set used in accounting calculations.
This can be used as an evidence and assurance that all wanted transactions
are included into calculations. This txn set checksum can be easily
link:../contrib/txn-set-checksum.sh[calculated] without Tackler.

Information provided by Git storage backend and Txn Set Checksum combined together creates
immutable and persistent evidence of used accounting data in calculations.

See `auditing` in link:./tackler.conf[tackler.conf], link:./docs/tep/tep-1007.adoc[TEP-1007: Txn Set Checksum],
link:../contrib/txn-set-checksum.sh[txn-set-checksum.sh]  and link:#examples[examples] section for further information.


=== Validation of accounts

In strict mode, Tackler will only accept pre-defined accounts.  Strict account name validation
makes it impossible that transaction would leak into unknown account.

If accounting system allows usage of undefined accounts and doesn't enforce account name validation, it is possible to
loose or leak value into unknown, not tracked accounts, even when transactions still balance internally perfectly.

See link:./accounts.conf[Chart of Accounts (accounts.conf)] for further info.


=== Validation of commodities

In addition to strict mode for accounts, tackler supports strict mode for commodities.  In fact, if strict mode for
accounts is activated, then it is also activated for commodities at the same time.

When strict mode is activated, it is possible to set configuration option that allows empty commodities
(e.g. value posts without unit or commodity).

See link:./accounts.conf[accounts.conf] for further info.


=== Proof of used reporting parameters

Accounting reports generated by Tackler include account selector checksum, when Txn Set Checksum is activated.

Account Selector checksum is checksum of conditions which is used to determine which accounts will be included
into reports and calculations. Account Selector Checksum is easier and more straight forward to audit
than verbatim listing of long and potentially complex accounts selector definition.

See `auditing` in link:./tackler.conf[tackler.conf], link:./docs/tep/tep-1007.adoc[TEP-1007: Txn Set Checksum]
and link:#examples[examples] section for further information.


=== Tackler's test setup

Tackler and it's test setup are open source, so it's possible to do external audit of code base, tests or both.

Tackler's code base is tested very extensively.  This includes near perfect test coverage and logical
features permutation coverage.  Tackler is also tested with very large transaction sets (up to one million 
transactions) to detect any anomalies with larger data sets.  Tackler's unit tests includes test cases 
up to one hundred thousand transactions.

For further info, see:

 * link:../tests/tests.adoc[Tackler Test Tracking Database (T3DB)]
 * link:../perf/results/readme.adoc[Performance Test Results]


== Examples of reports with audit metadata
[[examples]]

Below are links to test reports with audit metadata:

* link:../tests/audit/ok/audit-1E2-04.ref.bal.txt[Balance report with audit metadata]
* link:../tests/audit/ok/audit-1E2-04.ref.balgrp.txt[Balange-group report with audit metadata]
* link:../tests/audit/ok/audit-1E2-04.ref.reg.txt[Register report with audit metadata]
* link:../tests/audit/ok/audit-1E2-04.ref.equity.txn[Equity export with audit metadata]


Same information is available with JSON format for Server and Client API:

* link:../tests/audit/ok/audit-1E2-04.ref.bal.json[Balance JSON report with audit metadata]
* link:../tests/audit/ok/audit-1E2-04.ref.balgrp.json[Balange-group JSON report with audit metadata]
* link:../tests/audit/ok/audit-1E2-04.ref.reg.json[Register JSON report with audit metadata]


'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../LICENSE[License] for the specific language governing permissions and limitations under
the link:../LICENSE[License].
