= Identity export

Identity export produces output of input transactions as they are interpreted by Tackler.

This export is valid input for Tackler, so it can be used for example archiving purposes.

By Tackler's design constraints input order of transactions is not important.
So there should be a stable way to sort transactions if
internal order of identity export (e.g. order of txns during one day and without time information)
is important.  In that case it is mandatory to provide  unique sorting information for each transaction.

Transactions are sorted by using txn-components in following order to find sort order
(in case of previous components have produced "same" sort order):

 timestamp, code, description, uuid

Transactions must have UUIDs, if fully deterministic, stable
and "distributed transaction producers"-safe sort order is needed.


'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../LICENSE[License] for the specific language governing permissions and limitations under
the link:../LICENSE[License].
