= JSON report format

JSON is treated as Human Machine Interface, e.g. values etc.
are truncated the same way as with text output, and all data is represent as strings.

This means reports in JSON format should be ready to be displayed
to user by UI as it is without further processing.

JSON output does not contain null values, e.g. if field is null, it is dropped.

link:./client-api.adoc[Client API] lists used data models for JSON serialization.

== Example reports

Supported reports with JSON output are `balance`, `balance-group` and `register`.
Exports in Tackler journal format (`equity` and `identity`) are not supported with JSON.

=== Balance report

* link:../tests/commodity/ok/basic-03.ref.bal.json[Balance with commodities]
* link:../tests/audit/ok/audit-1E2-04.ref.bal.json[Balance with Metadata]

=== Balance Group report

* link:../tests/commodity/ok/basic-03.ref.balgrp.json[Balance-group with Commodities]
* link:../tests/audit/ok/audit-1E2-04.ref.balgrp.json[Balange-group with Metadata]

=== Register report

* link:../tests/commodity/ok/basic-03.ref.reg.json[Register report with Commodities]
* link:../tests/audit/ok/audit-1E2-04.ref.reg.json[Register report with Metadata]


'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../LICENSE[License] for the specific language governing permissions and limitations under
the link:../LICENSE[License].
