= Balance report

Balance report is sum of each accounts over selected transactions.

There are two sums in balance report. First (the leftmost) sum is sum of postings
which are directly debiting or crediting that account (account tree node).
If there are none such transactions,  then this first sum is zero.

Second sum is total sum for account tree (e.g. account as root and all its children).


== Balance report configuration

See link:tackler.conf[tackler.conf] and `reports.balance.*` for full
information of balance report configuration options.


=== Account filtering

Accounts for Balance report can be filtered with global
`reporting.accounts` (conf+cli) or report specific `reports.balance.accounts`
setting (conf-only).


== Example report

----
BALANCE
-------
                 1.00    333.00  a
                 0.00    332.00  a:a1
                 0.00    332.00  a:a1:a2
                27.40    327.40  a:a1:a2:b
               300.00    300.00  a:a1:a2:b:c
                 4.60      4.60  a:a1:a2:c
                 0.00   -333.00  e
              -322.00   -322.00  e:e0101
                -2.00     -2.00  e:e0102
                -9.00     -9.00  e:e0103
=====================
                 0.00
----

=== Example report with commodities

Below is example balance report with mixed commodities.

....
BALANCE
-------
                 0.00           3.00 ACME  Assets
                 3.00           3.00 ACME  Assets:Stocks
                 0.00        -359.75 EUR   Assets
              -359.75        -359.75 EUR   Assets:Cash
==========================
                 3.00 ACME
              -359.75 EUR
....


'''
Tackler is distributed on an *"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND*, either express or implied.
See the link:../LICENSE[License] for the specific language governing permissions and limitations under
the link:../LICENSE[License].
